build:
  environment:
    php:
      version: "7.2"
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      tests:
        override:
          - command: ./vendor/bin/phpunit --coverage-clover build/coverage.xml
            coverage:
              file: build/coverage.xml
              format: clover

filter:
    excluded_paths: [tests/*]
